/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Notarization } from "./Notarization";

export { Notarization__factory } from "./factories/Notarization__factory";
